### ISSUE TITLE
Suma de consecutivos

### ISSUE THREAD

**Issue by joslnunez** [digitalers/Java-2023#12]
**Dado un array de enteros, hacer una función o método que indique que rangos de números consecutivos dan como resultado la cantidad que se le pasa como parámetro:**

```java
    Ej: array = (6,7,5,4,3,1,2,3,5,6,7,9,0,0,1,2,4,1,2,3,5,1,2)
``` 
    
    sumar(13)

_Los elementos entre (0,1) suman 13
Los elementos entre (2,5) suman 13
Los elementos entre (3,7) suman 13
Los elementos entre (9,10) suman 13
Los elementos entre (12,19) suman 13
Los elementos entre (13,19) suman 13
Los elementos entre (14,19) suman 13
Los elementos entre (18,22) suman 13_
@digitalers/java2023

**Comment by gururoot** [comment]
> **Dado un array de enteros, hacer una función o método que indique que rangos de números consecutivos dan como resultado la cantidad que se le pasa como parámetro:**
> 
> ```java
>     Ej: array = (6,7,5,4,3,1,2,3,5,6,7,9,0,0,1,2,4,1,2,3,5,1,2)
> ```
> 
> ```
> sumar(13)
> ```
> 
> _Los elementos entre (0,1) suman 13 Los elementos entre (2,5) suman 13 Los elementos entre (3,7) suman 13 Los elementos entre (9,10) suman 13 Los elementos entre (12,19) suman 13 Los elementos entre (13,19) suman 13 Los elementos entre (14,19) suman 13 Los elementos entre (18,22) suman 13_ @digitalers/java2023

**Comment by LucasFerreyraB** [comment]
Hola profe, acá le dejo mi código correspondiente a la actividad requerida.

https://github.com/LucasFerreyraB/DigitalersEjercicios/tree/main/Ejercicio1

**Comment by ferm11n** [comment]
Buenas profe, adjunto url para la _solución de la actividad_ de la clase 5.

**LINK:** https://github.com/ferm11n/DigitalersEjerJava/blob/main/RangosConsecutivos/src/Main.java
